### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create the HTML and CSS necessary to hold the car.
- [x] Add in the car.
- [x] Position the car appropriately on the screen.
- [x] Fix up any styling.
- [x] Check for bugs.
