### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create classes for turning the car.
- [x] Add an event listener for arrow keys.
- [x] Have the event handler apply the turns to the car.
- [x] Add transitions for a smoother animation.
- [x] Check for bugs.
