### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create data model to record the car's position.
- [x] Give the car absolute positioning.
- [x] Use the `setInterval()` function to increment the car's position.
- [x] Bind the car's movement to an event listener for the spacebar.
- [x] Bug fixes.
